Fix doc path on SUSE distributions
The RPM macro %{_docdir} points to /usr/share/doc/packages/ on SUSE, on Fedora/RedHat it points to /usr/share/doc

QMake install doc files to /usr/share/doc. QMake does not know the distribution specific directories.

So RPM build fails on SUSE distros:

error: File not found: /home/abuild/rpmbuild/BUILDROOT/lpub3d-2.0.20.690-44.1.i386/usr/share/doc/packages/lpub3d